name: CI

on:
  workflow_dispatch:
    inputs:
      mongo_version: 
        type: string
        default: "r8.0.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: clone mongo sourcecode
        run: git clone https://github.com/mongodb/mongo.git
      - name: check out specific version
        run: git checkout tags/${{ inputs.mongo_version }} -b ${{ inputs.mongo_version }}
      - name: install python lib
        run: |
          cd mongo
          python -m pip install 'poetry==1.5.1'
          python -m poetry install --no-root --sync
        
      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
