name: mongo-no-avx-8.0.3

on:
  workflow_dispatch:
    inputs:
      mongo_version: 
        type: string
        default: "r8.0.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install apt
        run: sudo apt install -y libcurl4-openssl-dev libssl-dev
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: clone mongo sourcecode
        run: git clone https://github.com/mongodb/mongo.git
      - name: check out specific version
        working-directory: mongo
        run: git checkout tags/${{ inputs.mongo_version }} -b ${{ inputs.mongo_version }}
      - name: install python lib
        working-directory: mongo
        run: |
          python -m pip install 'poetry==1.5.1'
          python -m poetry install --no-root --sync
      - name: overwrite sconstruct
        run: |
          cp ${{ inputs.mongo_version }}/SConstruct mongo/SConstruct
      - name: build mongo
        working-directory: mongo
        run: |
          python buildscripts/scons.py install-mongod
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.mongo_version }}-no-avx
          path: |
            mongo/build/install/bin
