name: mongo-no-avx-8.0.3

on:
  workflow_dispatch:
    inputs:
      mongo_version: 
        type: string
        default: "r8.0.3"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - name: install apt
        run: sudo apt install -y libcurl4-openssl-dev libssl-dev
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          activate-environment: mongo
      - run: |
          conda info
          python --version
      - name: clone mongo sourcecode
        run: git clone https://github.com/mongodb/mongo.git
      - name: check out specific version
        working-directory: mongo
        run: git checkout tags/${{ inputs.mongo_version }} -b ${{ inputs.mongo_version }}
      - name: install python lib
        working-directory: mongo
        run: |
          export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          python -m pip install 'poetry==1.5.1'
          pip wheel --use-pep517 "zope-interface (==5.0.0)"    #separately install with pep517 flag since this cause error when install with poetry
          python -m poetry install --no-root --sync
      - run: python -c "import psutil"
      # - name: overwrite sconstruct
      #   run: |
      #     cp ${{ inputs.mongo_version }}/SConstruct mongo/SConstruct
      # - name: build mongo
      #   working-directory: mongo
      #   run: |
      #     export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
      #     python buildscripts/scons.py install-mongod --disable-warnings-as-errors
      # - name: Archive binary
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ inputs.mongo_version }}-no-avx
      #     path: |
      #       mongo/build/install/bin
